### PR TITLE
Add docker build

### PR DESCRIPTION
**Pull request by serbrech**
Added a simple Dockerfile and build.sh/build.ps1
Resulting image is `traefik-appinsights-watchdog:latest`  

`docker run --rm traefik-appinsights-watchdog:latest --appinsightskey XXXXXXXXX --debug`

### CODE REVIEW

**Comment by jjcollinge** [comment]
Worth pointing out that depending on network setup - traefikhealthendpoint (defaults to http://localhost:8080/health) will need to be overridden to point to correct Traefik host or container IP. Maybe add a section to README to clarify? Might make sense going forward for us to create a Makefile with various build targets (incl. Windows containers).

**Review by lawrencegripper — COMMENTED** [review]
LGTM

**Comment by lawrencegripper** [comment]
I'm happy to merge for the time being so we can use this for CI builds on PRs etc then look to doc as a deployment model in the future - sound good?

**Comment by jjcollinge** [comment]
Yes

**Pull request merged**
